export const serviceList = [
  "Advertising and Marketing",
  "Brand Identity",
  "Print Design",
  "Book Design & Editorial",
  "Motion Graphics",
  "Illustration",
  "Campaigns",
  "Data Driven Design",
  "Event Graphics",
  "Industrial Design",
  "Naming",
  "Packaging",
  "UI & Interaction Design",
  "Signage & Environmental",
  "Social Media",
  "Typography",
  "Web Design",
  "Video and Film",
];

export const industryList = [
  "Arts & Culture",
  "Banking & Finance",
  "Civic & Public",
  "Education",
  "Entertainment",
  "Food & Drink",
  "Healthcare",
  "Hospitality & Leisure",
  "Manufacturing & Industrials",
  "Media & Communication",
  "Not-for-Profit",
  "Professional Services",
  "Publishing",
  "Real Estate",
  "Fashion & Beauty",
  "Retail",
  "Technology",
  "Transport",
];
